export const RECORD_BOOK = 'RECORD_BOOK';
export const RECORD_MENU_STATE = 'RECORD_MENU_STATE'
export const RECORD_CURRENT_VOLUME_CHAPTERS='RECORD_CURRENT_VOLUME_CHAPTERS'
export const RECORD_BOOKSHELF_LIST = 'RECORD_BOOKSHELF_LIST';
export const GET_BOOKSELF_LIST = 'GET_BOOKSHELF_LIST';
